### ISSUE TITLE
Passing auth token is not documented

### ISSUE THREAD

**Issue by kibertoad** [adidas/safe-publish#3]
Passing auth token to npm is either not supported, or not documented. I assume using .npmrc is the only possible solution currently? How would one use this in CI environment utilizing secret passing via env values?

**Comment by moelders** [comment]
Thanks @kibertoad, I think we faced that issue when we were testing it, but we chose to create the `.npmrc` file in the end.
In CI, you can create the `.npmrc` dynamically, another option to test is to set an ENV variable.

**Comment by moelders** [comment]
No further action required, so I close the ticket. Thanks, @kibertoad.
